In [10]:
import plotly.express as px
import plotly.io as pio
import pandas as pd
import matplotlib.pyplot as plt
pio.renderers.default='notebook'

In [11]:
df = pd.read_csv("social_media_engagement.csv")

In [21]:
df['platform'].unique

<bound method Series.unique of 0      Facebook
1      Facebook
2     Instagram
3       Twitter
4       Twitter
        ...
95    Instagram
96      Twitter
97      Twitter
98    Instagram
99    Instagram
Name: platform, Length: 100, dtype: object>

In [23]:
fig = px.bar(df,x='post_type',y='likes',width=600,height=400,hover_data=['post_day','sentiment_score'],color='platform',color_discrete_map={'Facebook':'skyBlue','Instagram':'Pink','Twitter':'Black'})
fig.show()

In [29]:
fig = px.bar(df,x='post_type',y='likes',width=600,height=400,hover_data=['post_day','sentiment_score'],
             color='platform',color_discrete_sequence=['skyBlue','Pink','Black'],pattern_shape='sentiment_score',
             text_auto=True)
fig.show()

In [31]:
fig = px.bar(df,y='post_type',x='likes',width=600,height=400,hover_data=['post_day','sentiment_score'],
             color='platform',color_discrete_sequence=['skyBlue','Pink','Black'],pattern_shape='sentiment_score',
             text_auto=True,orientation='h')
fig.show()

In [32]:
df.columns

Index(['post_id', 'platform', 'post_type', 'post_time', 'likes', 'comments',
       'shares', 'post_day', 'sentiment_score'],
      dtype='object')

In [35]:
data=df.groupby('platform')[['likes','comments','shares']].mean()
data

                 likes    comments      shares
platform
Facebook   2699.750000  248.906250  474.375000
Instagram  2999.833333  232.444444  525.166667
Twitter    1368.593750  122.906250  233.718750

In [36]:
fig = px.bar(df,x='post_type',y=['likes','comments','shares'],width=600,height=400,hover_data=['post_day','sentiment_score'],
             color='platform',barmode='group')
fig.show()

In [37]:
fig = px.bar(df,x='post_type',y=['likes','comments','shares'],width=600,height=400,hover_data=['post_day','sentiment_score'],
             color='platform',barmode='stack')
fig.show()

In [39]:
fig = px.bar(df,x='post_type',y=['likes','comments','shares'],width=600,height=400,hover_data=['post_day','sentiment_score'],
             color='platform',barmode='relative',title='Bar chart')
fig.show()

In [40]:
fig= px.scatter(df,x='likes',y='comments',title='Simple Scatter plot')
fig.show()

In [41]:
fig= px.scatter(df,x='likes',y='comments',title='Group Scatter plot',color='platform')
fig.show()

In [42]:
fig= px.scatter(df,x='likes',y='comments',title='Bubble Scatter plot',color='platform',size='shares')
fig.show()

In [45]:
fig= px.scatter(df,x='likes',y='comments',title='Bubble Scatter plot',color='platform',size='shares',color_discrete_sequence=['skyBlue','hotPink','Black'])
fig.show()

In [46]:
fig= px.scatter(df,x='likes',y='comments',title='Bubble Scatter plot',color='platform',size='shares',
                color_discrete_sequence=['skyBlue','hotPink','Black'],facet_col='sentiment_score')
fig.show()

In [47]:
fig= px.scatter(df,x='likes',y='comments',title='Bubble Scatter plot',color='platform',size='shares',
                color_discrete_sequence=['skyBlue','hotPink','Black'],facet_row='sentiment_score')
fig.show()

In [50]:
fig= px.scatter_3d(df,x='likes',y='comments',z='shares',title='3D Scatter plot',color='platform')
fig.show()

In [53]:
fig= px.scatter_3d(df,x='likes',y='comments',z='shares',title='Bubble Scatter plot',color='platform',size='shares',
                color_discrete_sequence=['skyBlue','hotPink','Black'])
fig.show()

In [63]:
fig = px.scatter_matrix(df,dimensions=['likes','comments','shares'],color='platform',size='shares',
                color_discrete_sequence=['skyBlue','hotPink','black'])
fig.show()

In [64]:
fig = px.line(df,x='post_id',y='likes')
fig.show()

In [66]:
fig = px.line(df,x='post_id',y='likes',color='platform',markers=True)
fig.show()

In [67]:
data = px.data.tips()
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [80]:
fig = px.histogram(data,x='total_bill',y='tip',color='sex',nbins=50,histfunc='avg',pattern_shape='smoker',color_discrete_sequence=['hotpink','lightblue']) # sum,avg,mean,max,count
fig.show()

In [82]:
fig = px.pie(df,names='platform',values='likes',hole=0.5)
fig.show()

In [98]:
fig = px.pie(df,names='platform',values='likes')
fig.update_traces(textinfo='percent+label',textposition='outside',pull=[0.1,0,0])
fig.show()