In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv("imdb-top-1000.csv")
#print(data)
df=pd.DataFrame(data)
print(df)

                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
0    The Shawshank Redemption          1994      142   Drama          9.3
1               The Godfather          1972      175   Crime          9.2
2             The Dark Knight          2008      152  Action          9.0
3      The Godfather: Part II          1974      202   Crime          9.0
4                12 Angry Men          1957       96   Crime          9.0
..                        ...           ...      ...     ...          ...
995    Breakfast at Tiffany's          1961      115  Comedy          7.6
996                     Giant          1956      201   Drama          7.6
997     From Here to Eternity          1953      118   Drama          7.6
998                  Lifeboat          1944       97   Drama          7.6
999              The 39 Steps          1935       86   Crime          7.6

                 Director              Star1  No_of_Votes        Gross  \
0          Frank Darabont        Tim Robbins      2343110   28341469.0
1    Francis Ford Coppola      Marlon Brando      1620367  134966411.0
2       Christopher Nolan     Christian Bale      2303232  534858444.0
3    Francis Ford Coppola          Al Pacino      1129952   57300000.0
4            Sidney Lumet        Henry Fonda       689845    4360000.0
..                    ...                ...          ...          ...
995         Blake Edwards     Audrey Hepburn       166544  679874270.0
996        George Stevens   Elizabeth Taylor        34075  195217415.0
997        Fred Zinnemann     Burt Lancaster        43374   30500000.0
998      Alfred Hitchcock  Tallulah Bankhead        26471  852142728.0
999      Alfred Hitchcock       Robert Donat        51853  302787539.0

     Metascore
0         80.0
1        100.0
2         84.0
3         90.0
4         96.0
..         ...
995       76.0
996       84.0
997       85.0
998       78.0
999       93.0

[1000 rows x 10 columns]
               Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142   Drama          9.3
1             The Godfather          1972      175   Crime          9.2
2           The Dark Knight          2008      152  Action          9.0
3    The Godfather: Part II          1974      202   Crime          9.0
4              12 Angry Men          1957       96   Crime          9.0

               Director           Star1  No_of_Votes        Gross  Metascore
0        Frank Darabont     Tim Robbins      2343110   28341469.0       80.0
1  Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
2     Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
3  Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4          Sidney Lumet     Henry Fonda       689845    4360000.0       96.0

In [6]:
print(df.head())

               Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142   Drama          9.3
1             The Godfather          1972      175   Crime          9.2
2           The Dark Knight          2008      152  Action          9.0
3    The Godfather: Part II          1974      202   Crime          9.0
4              12 Angry Men          1957       96   Crime          9.0

               Director           Star1  No_of_Votes        Gross  Metascore
0        Frank Darabont     Tim Robbins      2343110   28341469.0       80.0
1  Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
2     Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
3  Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4          Sidney Lumet     Henry Fonda       689845    4360000.0       96.0

In [7]:
print(df.columns)

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [10]:
print(df['Genre'].unique)

<bound method Series.unique of 0       Drama
1       Crime
2      Action
3       Crime
4       Crime
        ...
995    Comedy
996     Drama
997     Drama
998     Drama
999     Crime
Name: Genre, Length: 1000, dtype: object>

In [17]:
g=df.groupby('Genre')
g.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [18]:
g.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [23]:
df.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [26]:
df.groupby('Genre')['Gross'].sum().sort_values().head(3)

Genre
Thriller      17550741.0
Western       58221508.0
Film-Noir    125910543.0
Name: Gross, dtype: float64

In [28]:
df.groupby('Genre')['IMDB_Rating'].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [32]:
df.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [33]:
df.groupby('Genre')['IMDB_Rating'].mean().max()

8.35

In [34]:
df.groupby('Director')['No_of_Votes'].sum()

Director
Aamir Khan              168895
Aaron Sorkin             89896
Abdellatif Kechiche     138741
Abhishek Chaubey         27175
Abhishek Kapoor          32628
                        ...
Zack Snyder            1233675
Zaza Urushadze           40382
Zoya Akhtar              99813
Çagan Irmak              78925
Ömer Faruk Sorak         56960
Name: No_of_Votes, Length: 548, dtype: int64

In [35]:
df.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [39]:
df.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False)

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Adventure    8.6
Animation    8.6
Comedy       8.6
Horror       8.5
Mystery      8.4
Fantasy      8.1
Film-Noir    8.1
Family       7.8
Thriller     7.8
Name: IMDB_Rating, dtype: float64

In [44]:
df.groupby('Star1')['Series_Title'].sum()

Star1
Aamir Khan              Dangal3 IdiotsRang De BasantiAndaz Apna ApnaPK...
Aaron Taylor-Johnson                                             Kick-Ass
Abhay Deol                                                          Dev.D
Abraham Attah                                         Beasts of No Nation
Adam Driver                                                Marriage Story
                                              ...
Zbigniew Zamachowski                                Trois couleurs: Blanc
Zooey Deschanel                                      (500) Days of Summer
Çetin Tekindor                                             Babam ve Oglum
Éric Toledano                                            The Intouchables
Ömer Faruk Sorak                                                Vizontele
Name: Series_Title, Length: 660, dtype: object

In [42]:
df.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [49]:
len(df.groupby('Genre'))

14

In [50]:
df.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [52]:
df.groupby('Genre').nunique()  # give count of all unique values

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [54]:
df.groupby('Genre').count()  # give count of all values available (it counts duplicate values also)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,172,172,172,172,172,172,172,143
Adventure,72,72,72,72,72,72,72,72,64
Animation,82,82,82,82,82,82,82,82,75
Biography,88,88,88,88,88,88,88,88,79
Comedy,155,155,155,155,155,155,155,155,125
Crime,107,107,107,107,107,107,107,107,87
Drama,289,289,289,289,289,289,289,289,241
Family,2,2,2,2,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,11,11,11,11,11,11,11
Mystery,12,12,12,12,12,12,12,12,8
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,4,4,4,4,4

In [61]:
df.groupby('Genre').nth([0,1])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [63]:
df.groupby('Genre').agg({'Runtime':['mean'],'IMDB_Rating':['mean'],'Gross':['sum']})

              Runtime IMDB_Rating         Gross
                 mean        mean           sum
Genre
Action     129.046512    7.949419  3.263226e+10
Adventure  134.111111    7.937500  9.496922e+09
Animation   99.585366    7.930488  1.463147e+10
Biography  136.022727    7.938636  8.276358e+09
Comedy     112.129032    7.901290  1.566387e+10
Crime      126.392523    8.016822  8.452632e+09
Drama      124.737024    7.957439  3.540997e+10
Family     107.500000    7.800000  4.391106e+08
Fantasy     85.000000    8.000000  7.827267e+08
Film-Noir  104.000000    7.966667  1.259105e+08
Horror     102.090909    7.909091  1.034649e+09
Mystery    119.083333    7.975000  1.256417e+09
Thriller   108.000000    7.800000  1.755074e+07
Western    148.250000    8.350000  5.822151e+07

In [68]:
df.groupby('Genre')['IMDB_Rating'].apply(lambda x:x.max()-x.min()) #Range of IMDB Rating

Genre
Action       1.4
Adventure    1.0
Animation    1.0
Biography    1.3
Comedy       1.0
Crime        1.6
Drama        1.7
Family       0.0
Fantasy      0.2
Film-Noir    0.3
Horror       0.9
Mystery      0.8
Thriller     0.0
Western      1.0
Name: IMDB_Rating, dtype: float64